version: "3"

services:
  ice:
    image: ghcr.io/lumiradio/icecast
    build:
      context: ./docker/icecast
      dockerfile: Dockerfile
    command: ["/bin/sh", "-c", "/usr/bin/icecast2 -c /etc/icecast2/icecast.xml"]
    ports:
      - 8000:8000
    volumes:
      - ./docker/icecast/icecast.xml:/etc/icecast2/icecast.xml
  redis:
    image: redis:7.0.11-alpine
  liquidsoap:
    image: ghcr.io/lumiradio/liquidsoap:${LIQUIDSOAP_TAG:-v1.0.6}
    build:
      context: ./docker/liquidsoap
      dockerfile: Dockerfile
    command: ["/usr/share/liquidsoap/script.liq"]
    volumes:
      - ./docker/liquidsoap/script.liq:/usr/share/liquidsoap/script.liq
      - ${RADIO_MUSIC:?RADIO_MUSIC is unset}:/music
      - ls_socket:/usr/share/liquidsoap
    environment:
      ICECAST_HOST: ${ICECAST_HOST:-ice}
      ICECAST_PORT: ${ICECAST_PORT:-8000}
      ICECAST_USER: ${ICECAST_USER:-source}
      ICECAST_PASSWORD: ${ICECAST_PASSWORD:-hackme}
      ICECAST_MOUNT: ${ICECAST_MOUNT:-lumiradio}
      LANGLEY_URL: http://langley:8000/played
    depends_on:
      - ice
  db:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
  byers:
    image: ghcr.io/lumiradio/lumiradio:${BYERS_TAG:-release}
    command: "./byers/byers"
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - 8181:8000
    depends_on:
      - liquidsoap
    environment:
      DISCORD_TOKEN: ${BYERS_DISCORD_TOKEN}
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@db/${PG_DATABASE}
      DISCORD__CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD__CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      SECRET: ${SECRET}
      REDIS_URL: redis://redis/
      RUST_LOG: info
      DISCORD__EMOJI__D6_1: ${DICE_ONE_EMOJI:-<:d6_1:1193962716038172732>}
      DISCORD__EMOJI__D6_2: ${DICE_TWO_EMOJI:-<:d6_2:1193962772455751820>}
      DISCORD__EMOJI__D6_3: ${DICE_THREE_EMOJI:-<:d6_3:1193962770308288543>}
      DISCORD__EMOJI__D6_4: ${DICE_FOUR_EMOJI:-<:d6_4:1193962769217761330>}
      DISCORD__EMOJI__D6_5: ${DICE_FIVE_EMOJI:-<:d6_5:1193962768097869834>}
      DISCORD__EMOJI__D6_6: ${DICE_SIX_EMOJI:-<:d6_6:1193962765937823805>}
      # SENTRY_DSN: ${SENTRY_DSN}
      # RUST_BACKTRACE: 1
    volumes:
      - ls_socket:/usr/src/app/ls
      - ${RADIO_MUSIC:?RADIO_MUSIC is unset}:/music
  langley:
    image: ghcr.io/lumiradio/lumiradio:${LANGLEY_TAG:-release}
    command: "./langley/langley"
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@db/${PG_DATABASE}
      REDIS_URL: redis://redis/
      RUST_LOG: info
  frohike:
    image: ghcr.io/lumiradio/lumiradio:${FROHIKE_TAG:-release}
    environment:
      RUST_LOG: debug
      REDIS_URL: redis://redis/
    command:
      - "./frohike/frohike"
      - "house-keeping"
      - "--database-url"
      - "postgres://${PG_USER}:${PG_PASSWORD}@db/${PG_DATABASE}"
      - "/music"
    volumes:
      - ${RADIO_MUSIC:?RADIO_MUSIC is unset}:/music

volumes:
  pg_data:
  liquidsoap:
  ls_socket:
